language: php

branches:
  only:
    - master
    - develop

php:
  - '5.6'

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - date
  - sudo apt-get update > /dev/null
  - composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

install:
  - date

  # Update node.js to 4.x
  - $TRAVIS_BUILD_DIR/ci/bin/install_nodejs.sh

  # Install Apache + extra PHP packages.
  - $TRAVIS_BUILD_DIR/ci/bin/install_apache.sh

  # Install drush.
  - $TRAVIS_BUILD_DIR/ci/bin/install_drush.sh

before_script:
  - date

script:
  - date

after_script:
  - date
