language: php

branches:
  only:
    - master
    - develop

php:
  - 5.6

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - date
  - sudo apt-get update > /dev/null
  - composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

install:
  - date

before_script:
  - date

script:
  - date

after_script:
  - date
